- hosts: all
  become: yes
  gather_facts: no
  pre_tasks:
  - name: Atualizando o repo
    raw: 'apt update'
  roles:
  - { role: install-k8s, tags: ["Install_k8s_role"] }
 
- hosts: k8s-master
  become: yes
  roles: 
  - { role: create-cluster, tags: ["Create_cluster_roles"] }

- hosts: k8s-workers
  become: yes
  roles:
  - { role: join-workers, tags: ["Join_workers_roles"] }